site_name: !ENV [SITE_NAME, "{{ site_settings.site_name }}"]
site_description: !ENV [SITE_DESCRIPTION, "{{ site_settings.site_description }}"]

theme:
  name: material
  logo: "{{ site_settings.logo }}"
  favicon: "{{ site_settings.logo }}"
  palette:
    - scheme: light
      primary: indigo
      accent: indigo
      navbar:
        background: '#000000'
    - scheme: dark
      primary: indigo
      accent: indigo
      navbar:
        background: '#000000'

docs_dir: docs
include:
  - admin/**
plugins:
  - search
  - awesome-pages
  - macros   # ← enable our macros

# We no longer need a static nav; awesome-pages will build it
