[build]
  command   = "pip install --upgrade pip && pip install -r requirements.txt && python main.py && mkdocs build"
  publish   = "site"

[build.environment]
  PYTHON_VERSION = "3.9"

[context.production.environment]
  GIT_GATEWAY_ENABLED = "true"

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/git-gateway/:splat"
  status = 200
  force  = true