backend:
  name: git-gateway
  branch: main

media_folder: "docs/images"
public_folder: "/images"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "docs/settings.yml"
        label: "Global Settings"
        name: "settings"
        fields:
          - { label: "Site Name",        name: "site_name",        widget: "string" }
          - { label: "Site Description", name: "site_description", widget: "text" }
          - { label: "Logo Path",        name: "logo",             widget: "string" }

  - name: "pages"
    label: "Pages"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body",  name: "body",  widget: "markdown" }